feat: 환경변수 Redirec URL 값을 바꾸는 로직 추가

diff --git a/backend/workflows/docker-cicd-backend.yml b/backend/workflows/docker-cicd-backend.yml
--- a/backend/workflows/docker-cicd-backend.yml
+++ b/backend/workflows/docker-cicd-backend.yml
@@ -11,14 +11,15 @@ on:
 
   workflow_dispatch:
     inputs:
-      env:
-        description: "배포 환경 선택"
+      redirect_url:
+        description: "(DEV일 때만 선택!) Redirect URL"
         required: true
-        default: "브랜치를 확인해주세요!"
+        default: "None"
         type: choice
         options:
-          - main
-          - develop
+          - None
+          - local
+          - dev
 
 jobs:
   backend-ci:
@@ -81,42 +82,42 @@ jobs:
 
           echo "::add-mask::${{ env.IMAGE_TAG }}"
           echo "::add-mask::${{ env.ENV_TAG }}"
-      
+
       - name: Fetch Environment Variables from SSM
         id: fetch-ssm-params
         run: |
-            ENV_PATH=""
-            if [ "${{ env.BRANCH }}" = "main" ]; then
-              ENV_PATH="/global/springboot/prod/"
-            else
-              ENV_PATH="/global/springboot/dev/"
+          ENV_PATH=""
+          if [ "${{ env.BRANCH }}" = "main" ]; then
+            ENV_PATH="/global/springboot/prod/"
+          else
+            ENV_PATH="/global/springboot/dev/"
+          fi
+
+          echo "🛠️ SSM에서 환경 변수 가져오는 중: $ENV_PATH"
+
+          # SSM 파라미터 가져오기 및 파싱
+          # `jq`는 JSON 파싱을 위해 필요합니다. `ubuntu-latest`에는 기본 설치되어 있습니다.
+          # 각 파라미터의 값을 명시적으로 마스킹 처리하고,
+          # Spring Boot 환경 변수 명명 규칙에 맞게 키를 변환하여 GITHUB_ENV에 추가합니다.
+          aws ssm get-parameters-by-path \
+            --path "$ENV_PATH" \
+            --recursive \
+            --with-decryption \
+            --query 'Parameters[*].{Name: Name, Value: Value}' | \
+            jq -r '.[] | (.Name | split("/") | last | gsub("[.-]";"_") | ascii_upcase) + "=" + .Value' > .env_temp
+
+          echo "📋 다음 환경 변수들을 테스트에 적용합니다:"
+          # .env_temp 파일의 각 라인을 읽어 환경 변수로 로드하고 마스킹 처리
+          while IFS='=' read -r key value; do
+            if [[ -n "$key" ]]; then
+              echo "::add-mask::$value" # 민감한 값은 로그에 마스킹 처리
+              echo "$key=$value" >> $GITHUB_ENV # 환경 변수로 설정
+              echo "$key=(masked)" # 로그에 설정된 변수 이름만 표시
             fi
-  
-            echo "🛠️ SSM에서 환경 변수 가져오는 중: $ENV_PATH"
-  
-            # SSM 파라미터 가져오기 및 파싱
-            # `jq`는 JSON 파싱을 위해 필요합니다. `ubuntu-latest`에는 기본 설치되어 있습니다.
-            # 각 파라미터의 값을 명시적으로 마스킹 처리하고,
-            # Spring Boot 환경 변수 명명 규칙에 맞게 키를 변환하여 GITHUB_ENV에 추가합니다.
-            aws ssm get-parameters-by-path \
-              --path "$ENV_PATH" \
-              --recursive \
-              --with-decryption \
-              --query 'Parameters[*].{Name: Name, Value: Value}' | \
-              jq -r '.[] | (.Name | split("/") | last | gsub("[.-]";"_") | ascii_upcase) + "=" + .Value' > .env_temp
-  
-            echo "📋 다음 환경 변수들을 테스트에 적용합니다:"
-            # .env_temp 파일의 각 라인을 읽어 환경 변수로 로드하고 마스킹 처리
-            while IFS='=' read -r key value; do
-              if [[ -n "$key" ]]; then
-                echo "::add-mask::$value" # 민감한 값은 로그에 마스킹 처리
-                echo "$key=$value" >> $GITHUB_ENV # 환경 변수로 설정
-                echo "$key=(masked)" # 로그에 설정된 변수 이름만 표시
-              fi
-            done < .env_temp
-            rm .env_temp # 임시 파일 삭제
+          done < .env_temp
+          rm .env_temp # 임시 파일 삭제
         working-directory: hertz-be/ # 프로젝트의 루트 디렉토리가 아닌 경우 설정
-  
+
       - name: Run All Tests (Unit and Integration)
         run: |
           echo "🛠️ 디버깅: 현재 환경 변수 확인..."
@@ -130,14 +131,13 @@ jobs:
         working-directory: hertz-be/ # 프로젝트의 루트 디렉토리가 아닌 경우 설정
         continue-on-error: true # 테스트 실패 시에도 다음 스텝으로 진행하도록 허용
 
-
       - name: Upload Test Report
         if: always()
         uses: actions/upload-artifact@v4
         with:
-            name: test-report-${{ github.sha }}
-            path: hertz-be/build/reports/tests/test/index.html # 실제 보고서 경로로 변경 필요
-            retention-days: 7 # 보고서 보관 기간 (선택 사항)
+          name: test-report-${{ github.sha }}
+          path: hertz-be/build/reports/tests/test/index.html # 실제 보고서 경로로 변경 필요
+          retention-days: 7 # 보고서 보관 기간 (선택 사항)
 
       # 5. Docker 빌드 및 푸시
       - name: Build and push Docker image
@@ -204,7 +204,7 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-         # 3. ECR 로그인
+          # 3. ECR 로그인
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
@@ -239,7 +239,7 @@ jobs:
 
           load_param "/global/GITHUB_TOKEN" GITHUB_TOKEN
           load_param "/global/TFC_TOKEN" TF_TOKEN_app_terraform_io
-          
+
           ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
           REPOSITORY=tuning-springboot
           IMAGE_TAG="${BRANCH}-${SHORT_SHA}"
@@ -266,7 +266,7 @@ jobs:
 
       - name: Setup gcloud CLI
         uses: google-github-actions/setup-gcloud@v1
-    
+
       - name: Install Terraform v1.11.3 manually
         run: |
           curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/1.11.3/terraform_1.11.3_linux_amd64.zip
@@ -276,27 +276,45 @@ jobs:
           export PATH="$HOME/bin:$PATH"   # 현재 step에 반영
           echo "$HOME/bin" >> $GITHUB_PATH
           terraform version
-      
+
+      # DEV 환경에서 FE 개발을 위한 Redirec URL 변경 로직
+      - name: Update SSM parameter
+        if: env.ENV == 'DEV'
+        run: |
+          if [[ "${{ github.event.inputs.redirect_url }}" == "local" ]]; then
+            REDIRECT_URL="${{ secrets.REDIRECT_URL_LOCAL }}"
+          elif [[ "${{ github.event.inputs.redirect_url }}" == "dev" ]]; then
+            REDIRECT_URL="${{ secrets.REDIRECT_URL_DEV }}"
+          else
+            echo "[ERROR]Redirect URL을 선택해주세요."
+            exit 1
+          fi
+
+          aws ssm put-parameter \
+            --name "${{ secrets.SSM_PATH_REDIRECT_URL }}" \
+            --value "$REDIRECT_URL" \
+            --type "SecureString" \
+            --overwrite
+
       - name: Check if backend_tg exists and fallback to full apply
         if: env.ENV == 'DEV'
         working-directory: tf-code/terraform/gcp/environments/develop
         run: |
-            terraform init -reconfigure
-  
-            echo "🔍 Terraform 리소스 존재 여부 확인 중..."
-  
-            if terraform state list | grep -q "module.backend_ig"; then
-              echo "✅ Terraform 리소스가 존재합니다. 배포를 시작합니다."
-            else
-              echo "⚠️ Terraform 리소스가 없습니다. 전체 apply를 수행합니다."
-              terraform apply -auto-approve
-            fi
+          terraform init -reconfigure
+
+          echo "🔍 Terraform 리소스 존재 여부 확인 중..."
+
+          if terraform state list | grep -q "module.backend_ig"; then
+            echo "✅ Terraform 리소스가 존재합니다. 배포를 시작합니다."
+          else
+            echo "⚠️ Terraform 리소스가 없습니다. 전체 apply를 수행합니다."
+            terraform apply -auto-approve
+          fi
 
       - name: Deploy to Dev Environment
         if: env.ENV == 'DEV'
         working-directory: tf-code/terraform/gcp/environments/develop
         run: |
-          
           terraform init -reconfigure
 
           echo "{" > 01-deployment.auto.tfvars.json
@@ -323,7 +341,6 @@ jobs:
           echo "⏱ 60초 대기 중... 인스턴스 초기화 및 헬스체크 준비"
           sleep 60
 
-
           echo "🩺 $MIG_NAME 인스턴스 헬스체크 시작..."
           sleep 60 # Wait for instances to initialize
 
@@ -346,22 +363,21 @@ jobs:
 
           echo "❌ ${RETRY}회 시도 후에도 MIG 인스턴스가 HEALTHY 상태가 아닙니다."
           exit 1
-      
+
       - name: Check if backend_tg exists and fallback to full apply
         if: env.ENV == 'PROD'
         working-directory: tf-code/terraform/gcp/environments/prod
         run: |
-            terraform init -reconfigure
-  
-            echo "🔍 Terraform 리소스 존재 여부 확인 중..."
-  
-            if terraform state list | grep -q "module.backend_tg"; then
-              echo "✅ Terraform 리소스가 존재합니다. 바로 배포를 시작합니다."
-            else
-              echo "⚠️ Terraform 리소스가 없습니다. 전체 apply를 수행합니다."
-              terraform apply -auto-approve
-            fi
-  
+          terraform init -reconfigure
+
+          echo "🔍 Terraform 리소스 존재 여부 확인 중..."
+
+          if terraform state list | grep -q "module.backend_tg"; then
+            echo "✅ Terraform 리소스가 존재합니다. 바로 배포를 시작합니다."
+          else
+            echo "⚠️ Terraform 리소스가 없습니다. 전체 apply를 수행합니다."
+            terraform apply -auto-approve
+          fi
 
       - name: Get Active Deployment Color
         if: env.ENV == 'PROD'
@@ -372,7 +388,7 @@ jobs:
 
           BLUE_MAX=$(terraform output -json | jq -r '.blue_instance_count_backend.value.max')
           GREEN_MAX=$(terraform output -json | jq -r '.green_instance_count_backend.value.max')
-          
+
           echo "BLUE_MAX: $BLUE_MAX"
           echo "GREEN_MAX: $GREEN_MAX"
 
@@ -411,13 +427,12 @@ jobs:
           echo "  \"${TARGET}_instance_count_backend\": {\"min\": 1, \"max\": 2}," >> 01-deployment.auto.tfvars.json
           echo "  \"${ACTIVE}_instance_count_backend\": {\"min\": 1, \"max\": 2}" >> 01-deployment.auto.tfvars.json
           echo "}" >> 01-deployment.auto.tfvars.json
-          
-          
+
           cat 01-deployment.auto.tfvars.json
           terraform apply -auto-approve \
             -target=module.backend_tg \
             -target=module.backend_internal_asg_${TARGET}
-          
+
           echo "💾 Output 적용 중 ..."
           terraform apply -refresh-only -auto-approve
           terraform output -json
@@ -470,7 +485,7 @@ jobs:
         working-directory: tf-code/terraform/gcp/environments/prod
         run: |
           terraform init -reconfigure
-            
+
           BLUE_MAX=$(terraform output -json | jq -r '.blue_instance_count_backend.value.max')
           GREEN_MAX=$(terraform output -json | jq -r '.green_instance_count_backend.value.max')
           echo "BLUE_MAX-before-half: $BLUE_MAX"
@@ -516,7 +531,7 @@ jobs:
           echo "}" >> 04-scale-down.auto.tfvars.json
           terraform apply -auto-approve \
             -target=module.backend_internal_asg_${ACTIVE}.google_compute_region_autoscaler.this \
-          
+
           echo "💾 Output 적용 중 ..."
           terraform apply -refresh-only -auto-approve
           terraform output -json
@@ -620,13 +635,13 @@ jobs:
         uses: google-github-actions/auth@v1
         with:
           credentials_json: "${{ env.SA_KEY }}"
-      
+
       - name: Install Terraform CLI manually
         run: |
-            curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/1.11.3/terraform_1.11.3_linux_amd64.zip
-            unzip terraform.zip
-            sudo mv terraform /usr/local/bin/
-            terraform -version
+          curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/1.11.3/terraform_1.11.3_linux_amd64.zip
+          unzip terraform.zip
+          sudo mv terraform /usr/local/bin/
+          terraform -version
 
       - name: Send rollback start notification
         if: env.ENV == 'PROD'
